name: (Manual) 0 - Create new Site Instance
on: 
  workflow_dispatch:
    inputs:
      region:
        description: 'Region'
        required: true
        type: choice
        options: 
          - 'us'
          - 'ca'
          - 'eu'
          - 'au'
        default: 'us'
      do_notify:
        description: 'Notify Slack Deploy Channel?'
        required: true
        type: choice
        options: 
          - 'Yes'
          - 'No'
        default: 'Yes'
      site_name:
        description: 'Site Name:'
        required: true
      site_label:
        description: 'Site Label:'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
    - name: Deployment Processing
      id: branch-processor
      env:
        TERMINUS_MACHINE_TOKEN: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        ORG_UUID: ${{ secrets.ORG_UUID }}
        UPSTREAM_UUID: ${{ secrets.UPSTREAM_UUID }}
        REGION: ${{ github.event.inputs.region }}
        SITE_LABEL: ${{ github.event.inputs.site_label }}
        SITE_NAME: ${{ github.event.inputs.site_name }}
        DO_NOTIFY: ${{ github.event.inputs.do_notify }}
      run: |

        #!/bin/bash
        set +e
        
        if  [ $DO_NOTIFY == "Yes" ]
        then
          # Tell slack we're starting this site
          SLACK_START="------------- :building_construction: Creating new site - ${SITE_NAME}  :building_construction: ------------- \n"
          echo -e "Starting ${PANTHEON_SITE}";
          curl -X POST -H 'Content-type: application/json' --data "{'text':'${SLACK_START}'}" $SLACK_WEBHOOK
        fi

        terminus site:create --org $ORG_UUID --region $REGION -- $SITE_NAME '${SITE_LABEL}' $UPSTREAM_UUID
        #tag this site in Pantheon
        terminus tag:add $SITE_NAME GHA

        # get dashboard link by site_name
        DASHBOARD=$(terminus dashboard:view $SITE_NAME --print)
        SLACK="${SITE_LABEL} Site Creation Complete. ${DASHBOARD}"
        [ $DO_NOTIFY == "Yes" ] && curl -X POST -H 'Content-type: application/json' --data "{'text':'${SLACK}'}" $SLACK_WEBHOOK